import { Inter, Orbitron } from "next/font/google";
import "./globals.css";
import Navigation from "@/sections/Navigation";
import Footer from "@/sections/Footer";


const orbitron =Orbitron({subsets:["latin"]})

export const metadata = {
  title: "Skolars Entertainment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={orbitron.className}>
        <Navigation/>
        <div>{children}</div>
        <Footer/>
        </body>
    </html>
  );
}
